const abilities = [
  { name: 'Java', width: '75%' },
  { name: 'Javascript', width: '85%' },
  { name: 'Typescript', width: '85%' },
  { name: 'Spring Boot', width: '85%' },
  { name: 'React', width: '85%' },
  { name: 'Angular', width: '80%' },
  { name: 'JQuerry', width: '80%' },
  { name: 'Html5', width: '90%' },
  { name: 'CSS', width: '90%' },
  { name: 'SASS', width: '90%' },
  { name: 'Bootstrap', width: '85%' },
  { name: 'Material UI', width: '85%' },
  { name: 'Mysql', width: '85%' },
  { name: 'PostgreSQL', width: '85%' },
  { name: 'MongoDb', width: '80%' },
  { name: 'Firebase', width: '60%' },
  { name: 'Wordpress', width: '90%' },
  { name: 'Corel Draw', width: '90%' },
  { name: 'Illustrator', width: '90%' },
  { name: 'Revit', width: '70%' },
  { name: 'Excel', width: '90%' },
  { name: 'Inglês', width: '85%' },
  { name: 'Francês', width: '75%' },
];

export default abilities;
